version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: voteness
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: voteness
      DATABASE_PASSWORD: voteness
    links:
      - mongo:mongo
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: voteness
      MONGO_INITDB_ROOT_PASSWORD: voteness
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'